services:
  postgres:
    build:
      context: .
      dockerfile: postgres.dockerfile
    image: "postgres-tutorials"
    container_name: postgres-lph
    environment:
      - POSTGRES_USER=fastapi_traefik_prod
      - POSTGRES_PASSWORD=fastapi_traefik_prod
      - POSTGRES_DB=fastapi_traefik_prod
    volumes:
       - dbtuto:/data/postgres-tuto
    expose:
      - 5432
    restart: unless-stopped
volumes:
    dbtuto:
      external: true