FROM tiangolo/uvicorn-gunicorn:python3.10-slim

# Install necessary system dependencies
RUN apt-get update && \
    apt-get install -y netcat-traditional build-essential gcc g++ make libffi-dev libssl-dev git && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir pycryptodome && \
    pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .